const data = {
  shops: [
    {
      _id: 1,
      name: 'Restaurante El Salvador',
      slug: 'restaurante-el-salvador',
      image: '/images/shops/1.png',
      address: 'C/ Ayala, 10',
      city: 'Don Benito',
      locality: 'Badajoz',
      postcode: '06400',
      email: 'test@example.com',
      phone1: '600000000',
      phone2: '611111111',
      locationLA: 38.961577,
      locationLO: -5.860242,
      cart: 1,
      menu: 1,
    },
    {
      _id: 2,
      name: 'Bar El Banderín',
      slug: 'bar-el-banderin',
      image: '/images/shops/2.png',
      address: 'C/ Ramón y Cajal, 24',
      city: 'Don Benito',
      locality: 'Badajoz',
      postcode: '06400',
      email: 'test2@example2.com',
      phone1: '622222222',
      phone2: '633333333',
      locationLA: 38.961577,
      locationLO: -5.860242,
      cart: 2,
      menu: 2,
    },
  ],
  carts: [
    {
      _id: 1,
      items: [
        {
          _id: 1,
          name: 'Tortilla Española',
          slug: 'tortilla-espanola',
          category: 'Entrantes',
          image: '/images/p1.jpg',
          price: 6,
          isAvailable: true,
          description:
            'Deliciosa tortilla española hecha en el momento. Atención: no lleva cebolla.',
          alergenos: {
            isGluten: true,
            isMarisco: false,
            isHuevos: true,
            isPescado: false,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: true,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: false,
            isVegetariano: true,
            isVegano: false,
          },
        },
        {
          _id: 2,
          name: 'Surtido de Ibéricos',
          slug: 'surtido-ibericos',
          category: 'Entrantes',
          image: '/images/p2.jpg',
          price: 9,
          isAvailable: true,
          description:
            'Queso semicurado con surtido de ibéricos de jamón y lomo.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: true,
            isSoja: true,
            isLacteos: true,
            isFrutosSecos: true,
            isApio: true,
            isMostaza: true,
            isGranosSesamo: true,
            isSulfitos: true,
            isAltramuces: true,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 3,
          name: 'Sopa Castellana',
          slug: 'sopa-castellana',
          category: 'Puchero',
          image: '/images/p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa castellana, ideal para días fríos.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 4,
          name: 'Ensalada César',
          slug: 'ensalada-cesar',
          category: 'Ensaladas',
          image: '/images/p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensalada césar para 2 personas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 5,
          name: 'Entrecot de Ternera',
          slug: 'entrecot-ternera',
          category: 'Carnes',
          image: '/images/p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso entrecot de ternera cocinado a su gusto.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 6,
          name: 'Pluma Ibérica',
          slug: 'pluma-iberica',
          category: 'Carnes',
          image: '/images/p6.jpg',
          price: 16,
          isAvailable: true,
          description:
            'Deliciosa pluma ibérica con guarnición de patatas fritas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo',
          category: 'Postres',
          image: '/images/p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche',
          category: 'Postres',
          image: '/images/p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
      ],
    },
    {
      _id: 2,
      items: [
        {
          _id: 1,
          name: 'Tortilla Francesa',
          slug: 'tortilla-francesa',
          category: 'Entrantes',
          image: '/images/p1.jpg',
          price: 6,
          isAvailable: true,
          description: 'Deliciosa tortilla francesa hecha en el momento.',
          alergenos: {
            isGluten: true,
            isMarisco: false,
            isHuevos: true,
            isPescado: false,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: true,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: false,
            isVegetariano: true,
            isVegano: false,
          },
        },
        {
          _id: 2,
          name: 'Surtido de Quesos',
          slug: 'surtido-quesos',
          category: 'Entrantes',
          image: '/images/p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Quesos semicurados en surtido.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: true,
            isSoja: true,
            isLacteos: true,
            isFrutosSecos: true,
            isApio: true,
            isMostaza: true,
            isGranosSesamo: true,
            isSulfitos: true,
            isAltramuces: true,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 3,
          name: 'Sopa Gallega',
          slug: 'sopa-gallega',
          category: 'Puchero',
          image: '/images/p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa gallega, ideal para días fríos.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 4,
          name: 'Ensaladilla Rusa',
          slug: 'ensaladilla-rusa',
          category: 'Ensaladas',
          image: '/images/p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensaladilla rusa para 2 personas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 5,
          name: 'Solomillo de Cerdo',
          slug: 'solomillo-cerdo',
          category: 'Carnes',
          image: '/images/p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso solomillo de cerdo cocinado a su gusto.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 6,
          name: 'Secreto Ibérico',
          slug: 'secreto-iberico',
          category: 'Carnes',
          image: '/images/p6.jpg',
          price: 16,
          isAvailable: true,
          description:
            'Delicioso secreto ibérico con guarnición de patatas fritas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo',
          category: 'Postres',
          image: '/images/p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche',
          category: 'Postres',
          image: '/images/p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
      ],
    },
  ],
  menus: [
    {
      _id: 1,
      items: [
        {
          _id: 1,
          name: 'Tortilla',
          slug: 'tortilla',
          category: 'Primeros',
          image: '/images/p1.jpg',
          price: 6,
          isAvailable: true,
          description:
            'Deliciosa tortilla hecha en el momento. Atención: no lleva cebolla.',
          alergenos: {
            isGluten: true,
            isMarisco: false,
            isHuevos: true,
            isPescado: false,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: true,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: false,
            isVegetariano: true,
            isVegano: false,
          },
        },
        {
          _id: 2,
          name: 'Surtido',
          slug: 'surtido',
          category: 'Primeros',
          image: '/images/p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Surtido de ibéricos.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: true,
            isSoja: true,
            isLacteos: true,
            isFrutosSecos: true,
            isApio: true,
            isMostaza: true,
            isGranosSesamo: true,
            isSulfitos: true,
            isAltramuces: true,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 3,
          name: 'Sopa',
          slug: 'sopa',
          category: 'Primeros',
          image: '/images/p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa, ideal para días fríos.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 4,
          name: 'Ensalada',
          slug: 'ensalada',
          category: 'Primeros',
          image: '/images/p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensalada para 2 personas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 5,
          name: 'Entrecot',
          slug: 'entrecot',
          category: 'Segundos',
          image: '/images/p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso entrecot cocinado a su gusto.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 6,
          name: 'Pluma',
          slug: 'pluma',
          category: 'Segundos',
          image: '/images/p6.jpg',
          price: 16,
          isAvailable: true,
          description: 'Deliciosa pluma con guarnición de patatas fritas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 7,
          name: 'Clara de Huevo',
          slug: 'clara-huevo',
          category: 'Postres',
          image: '/images/p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Deliciosa clara de huevo casera.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 8,
          name: 'Vaso de Leche',
          slug: 'vaso-leche',
          category: 'Postres',
          image: '/images/p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Vaso con leche y un toque de canela.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
      ],
    },
    {
      _id: 2,
      items: [
        {
          _id: 1,
          name: 'Francesa',
          slug: 'francesa',
          category: 'Primeros',
          image: '/images/p1.jpg',
          price: 6,
          isAvailable: true,
          description: 'Deliciosa tortilla hecha en el momento.',
          alergenos: {
            isGluten: true,
            isMarisco: false,
            isHuevos: true,
            isPescado: false,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: true,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: false,
            isVegetariano: true,
            isVegano: false,
          },
        },
        {
          _id: 2,
          name: 'Quesos',
          slug: 'quesos',
          category: 'Primeros',
          image: '/images/p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Quesos en surtido.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: true,
            isSoja: true,
            isLacteos: true,
            isFrutosSecos: true,
            isApio: true,
            isMostaza: true,
            isGranosSesamo: true,
            isSulfitos: true,
            isAltramuces: true,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 3,
          name: 'Pulpo a la Gallega',
          slug: 'pulpo-gallega',
          category: 'Segundos',
          image: '/images/p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Pulpo a la gallega, ideal para días fríos.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 4,
          name: 'Ensaladilla',
          slug: 'ensaladilla',
          category: 'Primeros',
          image: '/images/p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensaladilla para 2 personas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 5,
          name: 'Solomillo',
          slug: 'solomillo',
          category: 'Segundos',
          image: '/images/p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso solomillo cocinado a su gusto.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 6,
          name: 'Secreto',
          slug: 'secreto',
          category: 'Segundos',
          image: '/images/p6.jpg',
          price: 16,
          isAvailable: true,
          description: 'Delicioso secreto con guarnición de patatas fritas.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo',
          category: 'Postres',
          image: '/images/p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
        {
          _id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche',
          category: 'Postres',
          image: '/images/p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          alergenos: {
            isGluten: true,
            isMarisco: true,
            isHuevos: true,
            isPescado: true,
            isCacahuetes: false,
            isSoja: false,
            isLacteos: false,
            isFrutosSecos: false,
            isApio: false,
            isMostaza: false,
            isGranosSesamo: false,
            isSulfitos: false,
            isAltramuces: false,
            isMoluscos: true,
            isVegetariano: false,
            isVegano: false,
          },
        },
      ],
    },
  ],
};

export default data;
