import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      //_id: 1,
      name: 'Angel',
      email: 'angel@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      plan: 'premium',
      surname: 'Castillo',
    },
    {
      //_id: 2,
      name: 'Alfonso',
      email: 'alfonso@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      plan: 'basic',
      shops: ['restaurante-el-salvador'],
      language: 'en',
    },
    {
      //_id: 3,
      name: 'Beatriz',
      email: 'bea@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      plan: 'premium',
      shops: ['bar-el-banderin'],
    },
  ],
  shops: [
    {
      //_id: 1,
      name: 'Restaurante El Salvador',
      slug: 'restaurante-el-salvador',
      image: 'profile-shop-default.png',
      address: 'C/ Ayala, 10',
      city: 'Don Benito',
      locality: 'Badajoz',
      postcode: '06400',
      email: 'test@example.com',
      phone1: '600000000',
      phone2: '611111111',
      views: 0,
      urlgmaps: '',
      languages: ['pt'],
      currency: '£',
      decimals: 2,
      facebook: '',
      instagram: '',
      twitter: '',
      youtube: '',
      tiktok: '',
    },
    {
      //_id: 2,
      name: 'Bar El Banderín',
      slug: 'bar-el-banderin',
      image: 'profile-shop-default.png',
      address: 'C/ Ramón y Cajal, 24',
      city: 'Don Benito',
      locality: 'Badajoz',
      postcode: '06400',
      email: 'test2@example2.com',
      phone1: '622222222',
      phone2: '633333333',
      views: 0,
      urlgmaps: 'https://g.page/r/CTaOQH6JFzZvEAg',
      languages: ['en', 'fr'],
      decimals: 2,
      facebook: '',
      instagram: '',
      twitter: '',
      youtube: '',
      tiktok: '',
    },
  ],
  carts: [
    {
      name: 'Carta Restaurante',
      slug: 'carta-restaurante',
      shop: 'restaurante-el-salvador',
      items: [
        {
          //_id: 1,
          name: 'Tortilla Española',
          slug: 'tortilla-espanola',
          category: 'Entrantes',
          image: 'p1.jpg',
          price: 6,
          isAvailable: true,
          description:
            'Deliciosa tortilla española hecha en el momento. Atención: no lleva cebolla.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          formats: [
            {
              name: 'media ración',
              price: 3,
            },
          ],
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: false,
            isHuevosAlergeno: true,
            isPescadoAlergeno: false,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: true,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: false,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 2,
          name: 'Surtido de Ibéricos',
          slug: 'surtido-ibericos',
          category: 'Entrantes',
          image: 'p2.jpg',
          price: 9,
          isAvailable: true,
          description:
            'Queso semicurado con surtido de ibéricos de jamón y lomo.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: true,
            isSojaAlergeno: true,
            isLacteosAlergeno: true,
            isFrutosSecosAlergeno: true,
            isApioAlergeno: true,
            isMostazaAlergeno: true,
            isGranosSesamoAlergeno: true,
            isSulfitosAlergeno: true,
            isAltramucesAlergeno: true,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 3,
          name: 'Sopa Castellana',
          slug: 'sopa-castellana',
          category: 'Puchero',
          image: 'p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa castellana, ideal para días fríos.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 4,
          name: 'Ensalada César',
          slug: 'ensalada-cesar',
          category: 'Ensaladas',
          image: 'p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensalada césar para 2 personas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 5,
          name: 'Entrecot de Ternera',
          slug: 'entrecot-ternera',
          category: 'Carnes',
          image: 'p5.jpg',
          price: 18,
          isAvailable: true,
          aditionalInfo: 'Incluye patatas',
          description: 'Delicioso entrecot de ternera cocinado a su gusto.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 6,
          name: 'Pluma Ibérica',
          slug: 'pluma-iberica',
          category: 'Carnes',
          image: 'p6.jpg',
          price: 16,
          isAvailable: true,
          description:
            'Deliciosa pluma ibérica con guarnición de patatas fritas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo',
          category: 'Postres',
          image: 'p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          formats: [
            {
              name: 'para 2 personas',
              price: 7,
            },
            {
              name: 'para 4 personas',
              price: 9,
            },
          ],
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche-1',
          category: 'Postres',
          image: 'p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
      ],
    },
    {
      name: 'Carta de El Banderín',
      slug: 'carta-de-el-banderin',
      shop: 'bar-el-banderin',
      items: [
        {
          //_id: 1,
          name: 'Tortilla Francesa',
          slug: 'tortilla-francesa',
          category: 'Entrantes',
          image: 'p1.jpg',
          price: 6,
          isAvailable: true,
          description: 'Deliciosa tortilla francesa hecha en el momento.',
          views: 0,
          isVegetariano: true,
          isVegano: false,
          isFeatured: true,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: false,
            isHuevosAlergeno: true,
            isPescadoAlergeno: false,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: true,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: false,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 2,
          name: 'Surtido de Quesos',
          slug: 'surtido-quesos',
          category: 'Entrantes',
          image: 'p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Quesos semicurados en surtido.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: true,
            isSojaAlergeno: true,
            isLacteosAlergeno: true,
            isFrutosSecosAlergeno: true,
            isApioAlergeno: true,
            isMostazaAlergeno: true,
            isGranosSesamoAlergeno: true,
            isSulfitosAlergeno: true,
            isAltramucesAlergeno: true,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 3,
          name: 'Sopa Gallega',
          slug: 'sopa-gallega',
          category: 'Puchero',
          image: 'p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa gallega, ideal para días fríos.',
          views: 0,
          isVegetariano: false,
          isVegano: true,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 4,
          name: 'Ensaladilla Rusa',
          slug: 'ensaladilla-rusa',
          category: 'Ensaladas',
          image: 'p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensaladilla rusa para 2 personas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 5,
          name: 'Solomillo de Cerdo',
          slug: 'solomillo-cerdo',
          category: 'Carnes',
          image: 'p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso solomillo de cerdo cocinado a su gusto.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 6,
          name: 'Secreto Ibérico',
          slug: 'secreto-iberico',
          category: 'Carnes',
          image: 'p6.jpg',
          price: 16,
          isAvailable: true,
          description:
            'Delicioso secreto ibérico con guarnición de patatas fritas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo-1',
          category: 'Postres',
          image: 'p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche-2',
          category: 'Postres',
          image: 'p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
      ],
    },
  ],
  menus: [
    {
      name: 'Menú del Día',
      slug: 'menu-del-dia',
      shop: 'restaurante-el-salvador',
      items: [
        {
          //_id: 1,
          name: 'Tortilla',
          slug: 'tortilla',
          category: 'Primeros',
          image: 'p1.jpg',
          price: 6,
          isAvailable: true,
          description:
            'Deliciosa tortilla hecha en el momento. Atención: no lleva cebolla.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 2,
          name: 'Surtido',
          slug: 'surtido',
          category: 'Primeros',
          image: 'p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Surtido de ibéricos.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 3,
          name: 'Sopa',
          slug: 'sopa',
          category: 'Primeros',
          image: 'p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Sopa, ideal para días fríos.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 4,
          name: 'Ensalada',
          slug: 'ensalada',
          category: 'Primeros',
          image: 'p4.jpg',
          price: 6,
          isAvailable: true,
          aditionalInfo: 'Incluye aliño',
          description: 'Ensalada para 2 personas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 5,
          name: 'Entrecot',
          slug: 'entrecot',
          category: 'Segundos',
          image: 'p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso entrecot cocinado a su gusto.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 6,
          name: 'Pluma',
          slug: 'pluma',
          category: 'Segundos',
          image: 'p6.jpg',
          price: 16,
          isAvailable: true,
          description: 'Deliciosa pluma con guarnición de patatas fritas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 7,
          name: 'Clara de Huevo',
          slug: 'clara-huevo',
          category: 'Postres',
          image: 'p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Deliciosa clara de huevo casera.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 8,
          name: 'Vaso de Leche',
          slug: 'vaso-leche',
          category: 'Postres',
          image: 'p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Vaso con leche y un toque de canela.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
      ],
    },
    {
      name: 'Menú de El Banderín',
      slug: 'menu-de-el-banderin',
      shop: 'bar-el-banderin',
      items: [
        {
          //_id: 1,
          name: 'Francesa',
          slug: 'francesa',
          category: 'Primeros',
          image: 'p1.jpg',
          price: 6,
          isAvailable: true,
          description: 'Deliciosa tortilla hecha en el momento.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          formats: [
            {
              name: 'media tortilla',
              price: 3,
            },
          ],
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 2,
          name: 'Quesos',
          slug: 'quesos',
          category: 'Primeros',
          image: 'p2.jpg',
          price: 9,
          isAvailable: true,
          description: 'Quesos en surtido.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 3,
          name: 'Pulpo a la Gallega',
          slug: 'pulpo-gallega',
          category: 'Segundos',
          image: 'p3.jpg',
          price: 8.5,
          isAvailable: false,
          description: 'Pulpo a la gallega, ideal para días fríos.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 4,
          name: 'Ensaladilla',
          slug: 'ensaladilla',
          category: 'Primeros',
          image: 'p4.jpg',
          price: 6,
          isAvailable: true,
          description: 'Ensaladilla para 2 personas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 5,
          name: 'Solomillo',
          slug: 'solomillo',
          category: 'Segundos',
          image: 'p5.jpg',
          price: 18,
          isAvailable: true,
          description: 'Delicioso solomillo cocinado a su gusto.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 6,
          name: 'Secreto',
          slug: 'secreto',
          category: 'Segundos',
          image: 'p6.jpg',
          price: 16,
          isAvailable: true,
          description: 'Delicioso secreto con guarnición de patatas fritas.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 7,
          name: 'Flan de Huevo',
          slug: 'flan-huevo-3',
          category: 'Postres',
          image: 'p6.jpg',
          price: 5,
          isAvailable: true,
          description: 'Delicioso flan de huevo casero.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
        {
          //_id: 8,
          name: 'Arroz con Leche',
          slug: 'arroz-leche-3',
          category: 'Postres',
          image: 'p5.jpg',
          price: 7,
          isAvailable: true,
          description: 'Arroz con leche y un toque de canela.',
          views: 0,
          isVegetariano: false,
          isVegano: false,
          isFeatured: false,
          alergenos: {
            isGlutenAlergeno: true,
            isMariscoAlergeno: true,
            isHuevosAlergeno: true,
            isPescadoAlergeno: true,
            isCacahuetesAlergeno: false,
            isSojaAlergeno: false,
            isLacteosAlergeno: false,
            isFrutosSecosAlergeno: false,
            isApioAlergeno: false,
            isMostazaAlergeno: false,
            isGranosSesamoAlergeno: false,
            isSulfitosAlergeno: false,
            isAltramucesAlergeno: false,
            isMoluscosAlergeno: true,
          },
          trazas: {
            isGlutenTraza: true,
            isMariscoTraza: true,
            isHuevosTraza: true,
            isPescadoTraza: true,
            isCacahuetesTraza: false,
            isSojaTraza: false,
            isLacteosTraza: false,
            isFrutosSecosTraza: false,
            isApioTraza: false,
            isMostazaTraza: false,
            isGranosSesamoTraza: false,
            isSulfitosTraza: false,
            isAltramucesTraza: false,
            isMoluscosTraza: true,
          },
        },
      ],
    },
  ],
};

export default data;
